Movie_recommd/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myauth.urls')),
]

myauth/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


app_name = 'myauth'
urlpatterns = [
    path('remind/',views.remind,name='remind'),
    path('noticeUser/',views.noticeUser,name='noticeUser'),

    #用户
    path('',views.index,name='index'),
    path('slogin/',views.slogin,name='slogin'),
    path('slogout/',views.slogout,name='slogout'),
    path('register/',views.register,name='register'),
    path('user_center/',views.user_center,name='user_center'),
    path('user_center/edit_pro/',views.edit_pro,name='edit_pro'),
    path('user_center/change_pass/',views.change_pass,name='user_change_pass'),

    #电影
    path('showMovie/',views.showMovie,name='showMovie'),
    #path('movieRecommd/',views.movieRecommd,name='movieRecommd'),
    path('movieRecommd/hot',views.hot,name='hot'),
    path('movieRecommd/recommd1',views.recommd1,name='recommd1'),
    path('movieRecommd/recommd2',views.recommd2,name='recommd2'),
    path('movieRecommd/recommd3',views.recommd3,name='recommd3'),
    path('newMovie/',views.NEW_movie,name='NEW_movie'),

]

myauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

# Create your models here.

class commuser(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    nikname = models.CharField(blank=True,max_length=50)
    birthday = models.DateField(blank=True,null=True)
    class Meta:
        verbose_name_plural = '普通用户'


class movie_info(models.Model):
    movie_name = models.CharField(max_length=50)
    movie_poster = models.CharField(max_length=100)
    movie_description = models.TextField()
    movie_director = models.CharField(max_length=50)
    movie_Starring = models.CharField(max_length=100)
    movie_type = models.CharField(max_length=50)
    movie_point = models.FloatField(default='未评分')
    movie_address = models.CharField(max_length=50)

    def __str__(self):
        return self.movie_name

class User_evaluation(models.Model):
    user_id=models.FloatField()
    movie_id=models.FloatField()
    score = models.FloatField()
    class Meta:
        unique_together=('user_id','movie_id')


class MOVIE(models.Model):
    M_id = models.CharField(max_length=50)
    titles = models.CharField(max_length=100)
    release_time = models.CharField(max_length=50)
    director = models.CharField(max_length=50)
    times = models.CharField(max_length=50)
    tags = models.CharField(max_length=200)
    gerne = models.CharField(max_length=50)
    score = models.CharField(max_length=40)
    score_numbers = models.CharField(max_length=50)
    comments_num = models.CharField(max_length=50)
    five_stars = models.CharField(max_length=50)
    four_stars = models.CharField(max_length=50)
    three_stars = models.CharField(max_length=50)
    two_stars = models.CharField(max_length=50)
    one_star = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    jpg_url = models.CharField(max_length=200)

myauth/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django import forms

class selfchangeforms(UserChangeForm):
    nikname = forms.CharField(required=True,max_length=50)
    birthday = forms.DateField(required=True)

    class Meta:
        model= User
        fields=('username','password','email','nikname','birthday')


class selfforms(UserCreationForm):
    nikname = forms.CharField(required=True,max_length=50)
    birthday = forms.DateField(required=True)

    class Meta:
        model= User
        fields=('username','password1','password2','email','nikname','birthday')

myauth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from .forms import selfforms,selfchangeforms
from .models import commuser,movie_info,User_evaluation,MOVIE
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from math import *
from myauth.usercf import UserCF
from myauth.itemcf import ItemBasedCF
from myauth.svdrecommend import SVDrecommend
import pandas as pd
import numpy as np
# Create your views here.

def noticeUser(request):
    return render(request,'other/noticeUser.html')

def remind(request):
    return render(request,'other/remind.html')


@login_required(login_url='myauth:slogin')
def user_center(request):
    content = {'user':request.user}
    return render(request,'myauth/user_center.html',content)

#编辑个人信息
@login_required(login_url='myauth:slogin')
def edit_pro(request):
    if request.method == 'POST':
        changeform = selfchangeforms(request.POST,instance=request.user)
        if changeform.is_valid():
            changeform.save()
            return redirect('myauth:user_center')
    else:
        changeform = selfchangeforms(instance=request.user)

    contentform = {'changeform': changeform,'user':request.user}
    return render(request, 'myauth/edit_pro.html', contentform)


@login_required(login_url='myauth:slogin')
def change_pass(request):
    if request.method == 'POST':
        changepassform = PasswordChangeForm(data=request.POST, user=request.user)
        if changepassform.is_valid():
            changepassform.save()
            return redirect('myauth:slogin')
    else:
        changepassform = PasswordChangeForm(user=request.user)

    contentform = {'changepassform': changepassform, 'user': request.user}
    return render(request, 'myauth/change_pass.html', contentform)


import json
from django.forms.models import model_to_dict
#生成用户评分数据
import random
def load():
    id =int(1)
    vis = list(range(956))
    for i in range(1,956):
        vis[i]=0

    for x in range(10):
        for y in range(100):
            movie_id = random.randint(1,954)
            while vis[movie_id]==1:
                movie_id = random.randint(1,954)
            vis[movie_id]=1
            d = User_evaluation(user_id= id,movie_id=movie_id,score=round(random.uniform(5.0,10.0),1))
            d.save()
        id+=1
        print(id,'ok')
        for i in range(1,956):
            vis[i]=0
#下载图片
# 保存路径太长会导致出错
# 根据url在浏览器中打开网页，可以设定每次打开的间隔时间
#为了避免浏览器资源消耗完，每打开10个网页就关闭一次浏览器
import sys
import webbrowser
import time
import os
import urllib
def download():
    sys.path.append('libs')
    dataList = movie_info.objects.all()
    count=0
    for i in dataList:
        time.sleep(2)
        webbrowser.open(i.movie_poster,0,False)
        count+=1
        if count==10:
            count=0
            os.system('taskkill /F /IM chrome.exe')
        # print(i.movie_poster)
        # try:
        #     request = urllib.request.Request(i.movie_poster)
        #     response = urllib.request.urlopen(request)
        #     img = response.read()
        #     # print(img)
        #     with open("D:/pycharm_code/Movie_recommd/myauth/static/img/movie_info/" + str(i.id) + ".jpg", "wb") as f:
        #         f.write(img)
        #     print("D:/jpg/" + str(i.id) + ".jpg" + "已经写入本地磁盘")
        # except:
        #     print("访问为空")

#修改movie_id
def repair_id():
    data = movie_info.objects.all()
    cnt =1
    for x in data:
        x.id=cnt;
        x.save()
        cnt+=1


def index(request):
    #load()
    #   download()
    #repair_id()
    if request.user.is_authenticated==False:
         return render(request,'other/remind.html')

    error = ''
    if request.method=='POST':
        if request.POST.get('Score'):
            S = float(request.POST.get('Score'))
            if S>=0 and S<=10:
                num = User_evaluation.objects.filter(user_id=request.user.id,movie_id=request.POST.get('movie_id')).count()
                if num:
                    User_evaluation.objects.filter(user_id=request.user.id,movie_id=request.POST.get('movie_id')).update(score = request.POST.get('Score'))
                else:
                    d=User_evaluation(user_id=request.user.id, movie_id=request.POST['movie_id'],score=request.POST.get('Score'))
                    d.save()
            else:
                error='错误'
        key=request.POST['info']
    else:
        key='动作'
    data = movie_info.objects.filter(movie_type__regex=key)
    return render(request, 'myauth/index.html', {'data': data,'type':key,'error':error})

def slogin(request):
    if request.method=='POST':
        user = authenticate(request,username=request.POST['username'],password = request.POST['password'])
        if user is None:
            return render(request,'myauth/login.html',{'错误':'用户名不存在或者密码错误'})
        else:
            login(request,user=user)
            return redirect('myauth:index')
    else:
        return render(request,'myauth/login.html')


def slogout(request):
    logout(request)
    return redirect('myauth:index')

def register(request):
    if request.method == 'POST':
        registerform = selfforms(request.POST)
        if registerform.is_valid():
            registerform.save()
            user = authenticate(request, username=registerform.cleaned_data['username'], password=registerform.cleaned_data['password1'])
            user.email=registerform.cleaned_data['email']
            commuser(user=user,nikname=registerform.cleaned_data['nikname'],birthday=registerform.cleaned_data['birthday']).save()
            login(request,user)
            return redirect('myauth:index')
    else:
        registerform = selfforms()

    contentform ={'registerform':registerform}
    return render(request,'myauth/register.html',contentform)


#电影

def showMovie(request):
    if request.method == 'POST':
        error = ''
        if request.POST.get('movie_id'):
            movie_id = request.POST['movie_id']
            score = float(request.POST['Score'])
            if score >= 0 and score <= 10 :
                num = User_evaluation.objects.filter(user_id=request.user.id,movie_id=movie_id).count()
                if num:
                    User_evaluation.objects.filter(user_id=request.user.id,movie_id=movie_id).update(score=score)
                else:
                    User_evaluation(user_id=request.user.id, movie_id=movie_id,score=score).save()
            else:
                error = '错误'
            info = movie_info.objects.all()
            data = []
            data.append(info[int(movie_id)-1])
        else:
            movie_name = request.POST['movie_name']
            data = movie_info.objects.filter(movie_name=movie_name)
        if data:
            return render(request,'movie/show_movie.html',{'data':data,'error':error})
        else:
            return render(request, 'movie/show_movie.html', {'error':error})
    else:
        return redirect('myauth:index')


def NEW_movie(request):
    data = MOVIE.objects.all()[::-1][:10]
    return render(request,'movie/NEW_movie.html',{'data':data})

# def movieRecommd(request):
#     data = User_evaluation.objects.all()
#     return render(request,'movie/recommd.html',{'data':data})

def hot(request):
    data = movie_info.objects.filter(movie_type__regex='热门')
    return render(request,'movie/hot.html',{'data':data})

# 基于用户的协同过滤算法
def recommd1(request):
    userMovieScore = User_evaluation.objects.all()
    userMovieScoreDict = readData(userMovieScore)
    for i in userMovieScoreDict.items():
        print(i)
    userCF = UserCF(userMovieScoreDict)
    # 输入用户的id就是向该用户推荐电影
    if User_evaluation.objects.filter(user_id=request.user.id).count()== 0:
        return render(request, 'movie/recommd1.html', {'data': []})

    recommdResult = userCF.recommend(request.user.id)
    data = []  
    Movie = movie_info.objects.all()
    print(Movie[0])
    for x in recommdResult:
          data.append(Movie[int(x[0]-1)])
    return render(request,'movie/recommd1.html',{'data':data})

# 基于物品的协同过滤算法
def recommd2(request):
    userMovieScore = User_evaluation.objects.all()
    userMovieScoreDict = readData(userMovieScore)
    Item = ItemBasedCF(userMovieScoreDict)
    Item.ItemSimilarity()
    if User_evaluation.objects.filter(user_id=request.user.id).count()== 0:
        return render(request, 'movie/recommd2.html', {'data': []})
    # 输入用户的id就是向该用户推荐电影
    recommendDic = Item.Recommend(request.user.id)
    movie_list = []
    for i, score  in recommendDic.items():
        movie_list.append(i)
    data = []
    Movie = movie_info.objects.all()
    print(Movie[0])
    for x in movie_list:
        data.append(Movie[int(x) - 1])
    return render(request,'movie/recommd2.html',{'data':data})

# 基于SVD梯度下降的协同过滤算法
def recommd3(request):
    if User_evaluation.objects.filter(user_id=request.user.id).count()== 0:
        return render(request, 'movie/recommd3.html', {'data': []})
    userMovieScore = User_evaluation.objects.all()
    userMovieScoreDict = readData(userMovieScore)
    svd = SVDrecommend(userMovieScore, userMovieScoreDict)
    svd.read_data()
    recommend_movie_list = svd.recommend(request.user.id)
    data = []
    Movie = movie_info.objects.all()
    print(Movie[0])
    for x in recommend_movie_list:
        data.append(Movie[int(x) - 1])
    return render(request,'movie/recommd3.html',{'data':data})


# 从数据库中读取数据为用户电影评分字典
def readData(userMovieScore):
    data = {}
    for onedata in userMovieScore:
        # 每一行数据
        linedata = [onedata.user_id, onedata.movie_id, onedata.score]
        # print(linedata)
        # 如果字典中没有某位用户，则直接使用用户ID来创建这位用户
        if not linedata[0] in data.keys():
            data[linedata[0]] = {linedata[1]: linedata[2]}
        # 否则直接添加以该用户ID为key字典中
        else:

myauth/templates/myauth/change_pass.html
{% load static %}
<style type="text/css">
body {
    background-image: url("{% static 'img/showMovie/bg.jpg' %}");
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    color: #fff;
}
   .box a{
        {#color: beige;#}
        margin: 20px;
    }
    .box {
        width: 500px;
        margin: 10% auto;
        {#background-color: #fff;#}
    }
    .box h1 {
        margin: 10px;
    }
</style>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
    <link rel="stylesheet" href="//unpkg.com/layui@2.6.7/dist/css/layui.css">
</head>
<body>
<div class="layui-panel box">
    <h1>修改密码</h1>
    <a href="{% url 'myauth:index' %}">回到主页</a>
    <a href="{% url 'myauth:user_center' %}">个人中心</a>
    <a href="{% url 'myauth:edit_pro' %}">编辑个人信息</a>
    <a href="{% url 'myauth:user_change_pass' %}">修改密码</a>
    <a href="{% url 'myauth:slogout' %}">登出</a>
    <form action="" method="post">
        {% csrf_token %}
        {{ changepassform.as_p }}
        <button type="submit" class="layui-btn layui-btn-fluid">提交</button>
    </form>
</div>
</body>
</html>

myauth/templates/myauth/edit_pro.html
{% load static %}
<style type="text/css">
    body {
        background-image: url("{% static 'img/showMovie/bg.jpg' %}");
        background-position: center center;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        color: beige;
    }
   .box a{
        {#color: beige;#}
        margin: 20px;
    }
    .box {
        width: 400px;
        margin: 10% auto;
        {#background-color: #fff;#}
    }
    .box h1 {
        margin: 10px;
    }
        .form-box {
        margin-top: 20px;
    }
</style>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//unpkg.com/layui@2.6.7/dist/css/layui.css">
    <title>编辑个人信息</title>
</head>
<body>
<div class="layui-panel box">
    <h1>编辑个人信息</h1>
    <a href="{% url 'myauth:index' %}">回到主页</a>
    <a href="{% url 'myauth:user_center' %}">个人中心</a>
    <a href="{% url 'myauth:edit_pro' %}">编辑个人信息</a>
{#    <a href="{% url 'myauth:user_change_pass' %}">修改密码</a>#}
    <a href="{% url 'myauth:slogout' %}">登出</a>
    <form action="" method="post" class="form-box">
        {% csrf_token %}
        <div class="layui-form-item">
            <label class="layui-form-label">账号：</label>
            <div class="layui-input-inline">
              <input type="text" name="username" id="id_username" maxlength="50" value="{{ user.username }}" required lay-verify="required" placeholder="50个字符或者更少" autocomplete="off" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">电子邮件：</label>
            <div class="layui-input-inline">
              <input type="email" name="email" id="id_email" maxlength="50" value="{{ user.email }}" required lay-verify="required" placeholder="请输入邮箱" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">昵称：</label>
            <div class="layui-input-inline">
              <input type="text" name="nikname" id="id_nikname" value="{{ user.commuser.nikname }}" maxlength="50" required lay-verify="required" placeholder="50个字符或者更少" autocomplete="off" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">生日：</label>
            <div class="layui-input-inline">
              <input type="date" name="birthday" id="id_birthday" value="{{ user.commuser.birthday }}" required lay-verify="date" placeholder="yyyy-MM-dd" autocomplete="off" class="layui-input">
            </div>
        </div>

        <div class="btn-submit layui-btn layui-btn-fluid">
            <button type="submit" type="button" class="layui-btn layui-btn-radius" class="layui-btn layui-btn-sm">提交注册</button>
        </div>
{#        <p><label for="id_username">用户名:</label> <input type="text" name="username" value="{{ user.username }}" maxlength="150"#}
{#                                                        required id="id_username"> <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span>#}
{#        </p>#}
{#        <p><label for="id_email">电子邮件地址:</label> <input type="email" name="email" value="{{ user.email }}"#}
{#                                                        maxlength="254" id="id_email"></p>#}
{#        <p><label for="id_nikname">Nikname:</label> <input type="text" name="nikname" maxlength="50" required#}
{#                                                           id="id_nikname" value="{{ user.commuser.nikname }}"></p>#}
{#        <p><label for="id_birthday">Birthday:</label> <input type="date" name="birthday" required id="id_birthday" value="{{ user.commuser.birthday }}"></p>#}
{#        <button type="submit">提交</button>#}
    </form>
</div>
</body>
</html>

myauth/templates/myauth/index.html
{% load static %}
<style type="text/css">
body {
    background-image: url("{% static 'img/showMovie/bg.jpg' %}");
    {#background-color: #fff;#}
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    {#color: beige;#}
}
    a {
        {#color: beige;#}
        text-decoration: none;
    }

        .wrapper {
                margin-bottom: 8px;
            }
        .wrapper ul {
            display: table;		 /*这里是关键步骤：*/
            margin: 0 auto;      /*让ul在div中水平居中 */
             list-style: none;
        }
        .wrapper ul::after {     /*清除浮动 */
            content: '';
            display: inline-block;
            clear: both;
        }
        .wrapper ul li {
            float: left;         /*让li浮动起来 横向排列*/
            text-align: center;  /*让li在ul中水平居中*/
            height: 40px;
            line-height: 40px;   /*垂直居中*/
            width: 140px;        /*任意设置li的宽度，不设置宽度的话也可以设置padding*/
        }

     {#.movie {#}
     {#       border: 1px solid #000;#}
     {#   }#}
        .movie ul {
            display: table;		 /*这里是关键步骤：*/
            margin: 0 auto;      /*让ul在div中水平居中 */
            list-style: none;
            height: 500px;
        }
        .movie ul::after {     /*清除浮动 */
            content: '';
            display: inline-block;
            clear: both;
        }
        .movie ul li {
            float: left;         /*让li浮动起来 横向排列*/
            text-align: center;  /*让li在ul中水平居中*/
            height: 40px;
            line-height: 40px;   /*垂直居中*/
            width: 270px;        /*任意设置li的宽度，不设置宽度的话也可以设置padding*/
        }

        .showMovie{
            float: left;
            text-align: center;
        }
</style>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//unpkg.com/layui@2.6.7/dist/css/layui.css">
    <meta name="referrer" content="never">
    <title>电影推荐</title>
    <style>
       .left {
           margin: 20px;
           width: 40%;
           {#height: 200px;#}
           position: absolute;
           left: 0;
           top: 0;
           font-size:24px;
       }

       .middle {
           margin-top: 50px;
           width: 100%;
           height: 50px;
       }

       .right {
           margin: 20px;
           width: 40%;
           {#height: 200px;#}
           {#background: #FCC;#}
           position: absolute;
           right: 0;
           top: 0;
           font-size: 24px;
           text-align: right;
       }

       .right_search {
            {#position: relative;#}
            {#top: 80px;#}
            {#float: left;#}
            {#left: 300px;#}
        }
        {#.title {#}
        {#    font-size: 20px;#}
        {#}#}
        .box-top {
            margin: 20px auto;
            width: 90%;
            background-color: #fff;
            padding: 20px;
            height: 100px;
        }
        .clearfix:after{
             content:".";
             display:block;
             height:0;
             clear:both;
             visibility:hidden;
        }
       .middle .navbar .layui-input-inline {
            width: 90%;
        }
       .welcome {
           margin-right: 30px;
       }
       h4 {
           {#width: 200px;#}
           {#background-color: #46b8da;#}
           color: #fff;
           text-align: center;
       }
       .movie .showMovie .layui-input-inline {
            width: 100px;
        }
       .score {
           margin-bottom: 8px;
       }
        </style>
</head>
<body>

<div class="layui-panel box-top" style="position: relative">
    <div class="clearfix">
         <div class="left" >
            <span class="title">邮电影网</span>
            {% if user.is_authenticated %}
                <span class="welcome">欢迎你{{ user.username }}</span>
                <a href="{% url 'myauth:slogout' %}">登出</a>
                <a href="{% url 'myauth:user_center' %}">个人中心</a>
                <br>
            {% else %}
                <a href="{% url 'myauth:slogin' %}">登录</a>
                <a href="{% url 'myauth:register' %}">注册</a>
            {% endif %}
        </div>

        <div class="right">
            <a href="{% url 'myauth:hot' %}">查看推荐 &emsp;</a>
            <a href="{% url 'myauth:NEW_movie' %}">最新电影</a>
        </div>
    </div>


    <div class="middle">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="form-inline my-2 my-lg-0" method="post" action="{% url 'myauth:showMovie' %}">
                {% csrf_token %}
              <div class="right_search layui-input-inline">
                  <input class="form-control mr-sm-2 layui-input" name="movie_name" lay-verify="title"  autocomplete="off"  type="text" placeholder="请输入电影名" aria-label="Search">
              </div>
                <button class="btn btn-outline-success my-2 my-sm-0 layui-btn" type="submit">搜索</button>
            </form>
          </div>
        </nav>
    </div>

</div>

{% if error %}
    <script>
        alert('请输入0到10之间的数据')
    </script>
{% endif %}

{#电影导航#}
 <div class="wrapper">
        <ul>
            <li><form action="" method="post">
                {% csrf_token %}
                <input type="hidden" value="动作" name="info">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0 layui-btn layui-btn-normal" >动作</button>
            </form></li>

            <li><form action="" method="post">
                {% csrf_token %}
                <input type="hidden" value="剧情" name="info">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0 layui-btn layui-btn-normal" >剧情</button>
            </form></li>

           <li><form action="" method="post">
                {% csrf_token %}
                <input type="hidden" value="爱情" name="info">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0 layui-btn layui-btn-normal" >爱情</button>
            </form></li>

            <li><form action="" method="post">
                {% csrf_token %}
                <input type="hidden" value="喜剧" name="info">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0 layui-btn layui-btn-normal" >喜剧</button>
            </form></li>

            <li><form action="" method="post">
                {% csrf_token %}
                <input type="hidden" value="动画" name="info">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0 layui-btn layui-btn-normal" >动画</button>
            </form></li>

           <li><form action="" method="post">
                {% csrf_token %}
                <input type="hidden" value="科幻" name="info">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0 layui-btn layui-btn-normal" >科幻</button>
            </form></li>

            <li><form action="" method="post">
                {% csrf_token %}
                <input type="hidden" value="犯罪" name="info">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0 layui-btn layui-btn-normal" >犯罪</button>
            </form></li>

            <li><form action="" method="post">
                {% csrf_token %}
                <input type="hidden" value="恐怖" name="info">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0 layui-btn layui-btn-normal" >恐怖</button>
            </form></li>
        </ul>
 </div>


<div class="movie">
        <ul>
           {% for x in data %}
               <div class="showMovie">
                   <div class="card" style="width: 18rem;">
                       <img src="{{ x.movie_poster }}" class="card-img-top" alt="..." width="200px" height="300px">
                       <form action="{% url 'myauth:showMovie' %}" method="post">
                           {% csrf_token %}
                           <input type="hidden" value={{ x.movie_name }} name="movie_name">
                           <button type="submit" style="width: 200px;" class="layui-btn layui-btn-fluid">{{ x.movie_name }}</button>
                       </form>
                   </div>
                   <h4>大众评分：{{ x.movie_point }}</h4>
                 <form action="" method="post" class="score">
                       {% csrf_token %}
                         <input type="hidden" value={{ x.id }} name="movie_id">
                        <input type="hidden" value="{{ type }}" name="info">
{#                        <input type="number" step="0.1" name="Score" placeholder="请输入你的评分" />#}
                        <div class="layui-input-inline">
                            <input type="number" name="Score" placeholder="输入评分" lay-verify="required|phone" autocomplete="off" class="layui-input">
                        </div>
                       <button type="submit" class="btn btn-outline-success my-2 my-sm-0 layui-btn layui-btn-normal" onclick="submitAction">提交评分</button>
                   </form>
               </div>
           {% endfor %}
        </ul>
 </div>
<br>

</body>
<script src="//unpkg.com/layui@2.6.7/dist/layui.js"></script>
<script>

</script>
</html>

myauth/templates/myauth/user_center.html
{% load static %}
<style type="text/css">
body {
    background-image: url("{% static 'img/showMovie/bg.jpg' %}");
    {#background-color: #fff;#}
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    color: #fff;
}
   .box a{
        {#color: beige;#}
        margin: 20px;
    }
    .box {
        width: 400px;
        margin: 10% auto;
        {#background-color: #fff;#}
    }
    .box h1 {
        margin: 10px;
    }
    .info {
        margin: 20px;
    }
    .info p {
        margin-bottom: 10px;
    }
</style>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//unpkg.com/layui@2.6.7/dist/css/layui.css">
    <title>个人中心</title>
</head>
<body>
     <div class="layui-panel box">
        <h1>个人中心</h1>
        <a href="{% url 'myauth:index' %}">回到主页</a>
        <a href="{% url 'myauth:edit_pro' %}">编辑个人信息</a>
{#        <a href="{% url 'myauth:user_change_pass' %}">修改密码</a>#}
        <a href="{% url 'myauth:slogout' %}">登出</a>
        <div class="info">
            <p>用户名：{{ user.username }}</p>
            <p>邮箱：{{ user.email }}</p>
            <p>昵称：{{ user.commuser.nikname }}</p>
            <p>生日：{{ user.commuser.birthday }}</p>
        </div>
      </div>

</body>
</html>